import fs from "fs";
import path from "path";
import type { Track } from "@/lib/content";

/**
 * Resolves the pre-generated pronunciation clip for a vocab word / concept name
 * — the ▶ "hear it" button on the handout plays it. The clips are OpenAI-TTS
 * mp3s, committed + CDN-served under `public/audio/[junior/]<date>/<slug>.mp3`,
 * generated by scripts/gen-pronunciation.mjs.
 *
 * SERVER-ONLY (imports `fs`): only the server handout pages import this, so the
 * existence check runs at build/prerender time. There is NO browser-speech
 * fallback, so a term only gets a ▶ button when its clip actually exists on disk
 * — a missing clip means no button, never a dead one.
 *
 * The `slugify()` here MUST match scripts/gen-pronunciation.mjs's, or the handout
 * won't find the clips the script wrote.
 */
export const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

export function audioSrcFor(
  date: string,
  term: string,
  track: Track = "senior",
): string | undefined {
  const slug = slugify(term);
  // Junior clips live under an extra `junior/` segment; senior keeps today's path.
  const rel = track === "junior" ? `junior/${date}` : date;
  const file = path.join(process.cwd(), "public", "audio", rel, `${slug}.mp3`);
  return fs.existsSync(file) ? `/audio/${rel}/${slug}.mp3` : undefined;
}
